### PR TITLE
perf: ⚡️ reduce runtime about 100ms compare to main branch

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
image
image

**Comment by IWANABETHATGUY** [comment]
since the search_term is always the same , we could share the same `Vec<char>` array during the loop, compare to the last pr, thte runtime reduce about 100ms. The edit distance function of course benefit from this pr, since the we don't need the search_chars allocation any more.

**Comment by hisbaan** [comment]
Awesome, great work! If you could, please also update the `#Arguments` section of the docstring with the updated `serch_chars` argument and how to obtain it (`search_string.chars().collect()`) as this is a publicly exposed function

**Comment by hisbaan** [comment]
As a side note, how are you comparing benchmarks from one branch to another? It seems pretty useful for future optimizations

**Comment by IWANABETHATGUY** [comment]
> Awesome, great work! If you could, please also update the `#Arguments` section of the docstring with the updated `serch_chars` argument and how to obtain it (`search_string.chars().collect()`) as this is a publicly exposed function

finish that, but i am not a native speaker, so i can't guarantee that doc i wrote is expressed properly

**Pull request merged**
